version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "elixir"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      elixir:
        patterns: ["*"]
        update-types: ["minor", "patch"]
